# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ActionResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data",
    :"timestamp"
  ]

  @type t :: %__MODULE__{
    :"data" => [OpenXchangeClient.Model.EventData.t] | nil,
    :"timestamp" => integer() | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ActionResponse do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, OpenXchangeClient.Model.EventData, options)
  end
end

