# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.AppointmentListElement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"folder",
    :"recurrence_position",
    :"recurrence_date_position"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t,
    :"folder" => String.t,
    :"recurrence_position" => integer() | nil,
    :"recurrence_date_position" => integer() | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.AppointmentListElement do
  def decode(value, _options) do
    value
  end
end

