# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ChronosFreeBusyResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"attendee",
    :"freeBusyTime",
    :"warnings"
  ]

  @type t :: %__MODULE__{
    :"attendee" => OpenXchangeClient.Model.Attendee.t | nil,
    :"freeBusyTime" => [OpenXchangeClient.Model.FreeBusyTime.t] | nil,
    :"warnings" => [OpenXchangeClient.Model.Warning.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ChronosFreeBusyResponseData do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"attendee", :struct, OpenXchangeClient.Model.Attendee, options)
    |> deserialize(:"freeBusyTime", :list, OpenXchangeClient.Model.FreeBusyTime, options)
    |> deserialize(:"warnings", :list, OpenXchangeClient.Model.Warning, options)
  end
end

