# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ClientOnboardingDataDevices do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"enabled",
    :"platform",
    :"name",
    :"description",
    :"icon",
    :"scenarios"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"enabled" => boolean() | nil,
    :"platform" => String.t | nil,
    :"name" => String.t | nil,
    :"description" => String.t | nil,
    :"icon" => [String.t] | nil,
    :"scenarios" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ClientOnboardingDataDevices do
  def decode(value, _options) do
    value
  end
end

