# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ConfigProperty do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :name,
    :value
  ]

  @type t :: %__MODULE__{
          :name => String.t() | nil,
          :value => map() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ConfigProperty do
  def decode(value, _options) do
    value
  end
end
