# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ConversionBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"datasource",
    :"datahandler"
  ]

  @type t :: %__MODULE__{
    :"datasource" => OpenXchangeClient.Model.ConversionDataSource.t | nil,
    :"datahandler" => OpenXchangeClient.Model.ConversionDataHandler.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ConversionBody do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"datasource", :struct, OpenXchangeClient.Model.ConversionDataSource, options)
    |> deserialize(:"datahandler", :struct, OpenXchangeClient.Model.ConversionDataHandler, options)
  end
end

