# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.DateTimeData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :value,
    :tzid
  ]

  @type t :: %__MODULE__{
          :value => String.t() | nil,
          :tzid => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.DateTimeData do
  def decode(value, _options) do
    value
  end
end
