# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.DistributionListMember do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :folder_id,
    :display_name,
    :sort_name,
    :mail,
    :mail_field
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :folder_id => String.t() | nil,
          :display_name => String.t() | nil,
          :sort_name => String.t() | nil,
          :mail => String.t() | nil,
          :mail_field => float() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.DistributionListMember do
  def decode(value, _options) do
    value
  end
end
