# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.FileServiceConfiguration do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :widget,
    :name,
    :displayName,
    :mandatory,
    :options,
    :defaultValue
  ]

  @type t :: %__MODULE__{
          :widget => String.t() | nil,
          :name => String.t() | nil,
          :displayName => String.t() | nil,
          :mandatory => boolean() | nil,
          :options => map() | nil,
          :defaultValue => map() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.FileServiceConfiguration do
  def decode(value, _options) do
    value
  end
end
