# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.FindOptionsData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :timezone,
    :admin
  ]

  @type t :: %__MODULE__{
          :timezone => String.t() | nil,
          :admin => boolean() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.FindOptionsData do
  def decode(value, _options) do
    value
  end
end
