# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.FindFacetValueOption do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"filter"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"name" => String.t | nil,
    :"filter" => OpenXchangeClient.Model.FindFacetValueFilter.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.FindFacetValueOption do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"filter", :struct, OpenXchangeClient.Model.FindFacetValueFilter, options)
  end
end

