# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.FolderCheckLimitsResponseData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"errors"
  ]

  @type t :: %__MODULE__{
    :"errors" => [OpenXchangeClient.Model.FolderCheckLimitsResponseErrorData.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.FolderCheckLimitsResponseData do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"errors", :list, OpenXchangeClient.Model.FolderCheckLimitsResponseErrorData, options)
  end
end

