# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.FolderDataComOpenexchangeCalendarExtendedPropertiesUsedForSync do
  @moduledoc """
  Indicates whether the folder should be considered for synchronization with external clients or not.
  """

  @derive [Poison.Encoder]
  defstruct [
    :"value"
  ]

  @type t :: %__MODULE__{
    :"value" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.FolderDataComOpenexchangeCalendarExtendedPropertiesUsedForSync do
  def decode(value, _options) do
    value
  end
end

