# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.InlineResponse200Data do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"mailFolder",
    :"mailUID",
    :"id",
    :"folder_id",
    :"filename"
  ]

  @type t :: %__MODULE__{
    :"mailFolder" => String.t | nil,
    :"mailUID" => String.t | nil,
    :"id" => String.t | nil,
    :"folder_id" => String.t | nil,
    :"filename" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.InlineResponse200Data do
  def decode(value, _options) do
    value
  end
end

