# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.InlineObject3 do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"organizer",
    :"comment"
  ]

  @type t :: %__MODULE__{
    :"organizer" => OpenXchangeClient.Model.CalendarUser.t | nil,
    :"comment" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.InlineObject3 do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"organizer", :struct, OpenXchangeClient.Model.CalendarUser, options)
  end
end

