# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.LanguageData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"language_id",
    :"name",
    :"iso_639_1"
  ]

  @type t :: %__MODULE__{
    :"language_id" => integer() | nil,
    :"name" => String.t | nil,
    :"iso_639_1" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.LanguageData do
  def decode(value, _options) do
    value
  end
end

