# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MailAckBody do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :from,
    :folder,
    :id
  ]

  @type t :: %__MODULE__{
          :from => String.t() | nil,
          :folder => String.t() | nil,
          :id => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MailAckBody do
  def decode(value, _options) do
    value
  end
end
