# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MailDestinationData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"folder_id",
    :"id"
  ]

  @type t :: %__MODULE__{
    :"folder_id" => String.t | nil,
    :"id" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MailDestinationData do
  def decode(value, _options) do
    value
  end
end

