# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MailUpdateBody do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :folder_id,
    :color_label,
    :flags,
    :value,
    :set_flags,
    :clear_flags
  ]

  @type t :: %__MODULE__{
          :folder_id => String.t() | nil,
          :color_label => integer() | nil,
          :flags => integer() | nil,
          :value => boolean() | nil,
          :set_flags => integer() | nil,
          :clear_flags => integer() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MailUpdateBody do
  def decode(value, _options) do
    value
  end
end
