# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MailAccountData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"name",
    :"login",
    :"password",
    :"mail_url",
    :"mail_server",
    :"mail_port",
    :"mail_protocol",
    :"mail_secure",
    :"mail_starttls",
    :"mail_oauth",
    :"transport_url",
    :"transport_server",
    :"transport_port",
    :"transport_protocol",
    :"transport_secure",
    :"transport_login",
    :"transport_password",
    :"transport_auth",
    :"transport_starttls",
    :"transport_oauth",
    :"root_folder",
    :"primary_address",
    :"spam_handler",
    :"trash",
    :"sent",
    :"drafts",
    :"spam",
    :"confirmed_spam",
    :"confirmed_ham",
    :"unified_inbox_enabled",
    :"trash_fullname",
    :"sent_fullname",
    :"drafts_fullname",
    :"spam_fullname",
    :"confirmed_spam_fullname",
    :"confirmed_ham_fullname",
    :"pop3_refresh_rate",
    :"pop3_expunge_on_quit",
    :"pop3_delete_write_through",
    :"pop3_storage",
    :"pop3_path",
    :"personal",
    :"reply_to",
    :"addresses",
    :"meta",
    :"archive",
    :"archive_fullname"
  ]

  @type t :: %__MODULE__{
    :"id" => integer() | nil,
    :"name" => String.t,
    :"login" => String.t,
    :"password" => String.t,
    :"mail_url" => String.t,
    :"mail_server" => String.t | nil,
    :"mail_port" => integer() | nil,
    :"mail_protocol" => String.t | nil,
    :"mail_secure" => boolean() | nil,
    :"mail_starttls" => boolean() | nil,
    :"mail_oauth" => integer() | nil,
    :"transport_url" => String.t | nil,
    :"transport_server" => String.t | nil,
    :"transport_port" => integer() | nil,
    :"transport_protocol" => String.t | nil,
    :"transport_secure" => boolean() | nil,
    :"transport_login" => String.t | nil,
    :"transport_password" => String.t | nil,
    :"transport_auth" => String.t | nil,
    :"transport_starttls" => boolean() | nil,
    :"transport_oauth" => integer() | nil,
    :"root_folder" => String.t | nil,
    :"primary_address" => String.t,
    :"spam_handler" => String.t | nil,
    :"trash" => String.t | nil,
    :"sent" => String.t | nil,
    :"drafts" => String.t | nil,
    :"spam" => String.t | nil,
    :"confirmed_spam" => String.t | nil,
    :"confirmed_ham" => String.t | nil,
    :"unified_inbox_enabled" => boolean() | nil,
    :"trash_fullname" => String.t | nil,
    :"sent_fullname" => String.t | nil,
    :"drafts_fullname" => String.t | nil,
    :"spam_fullname" => String.t | nil,
    :"confirmed_spam_fullname" => String.t | nil,
    :"confirmed_ham_fullname" => String.t | nil,
    :"pop3_refresh_rate" => integer() | nil,
    :"pop3_expunge_on_quit" => boolean() | nil,
    :"pop3_delete_write_through" => boolean() | nil,
    :"pop3_storage" => String.t | nil,
    :"pop3_path" => String.t | nil,
    :"personal" => String.t | nil,
    :"reply_to" => String.t | nil,
    :"addresses" => String.t | nil,
    :"meta" => String.t | nil,
    :"archive" => String.t | nil,
    :"archive_fullname" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MailAccountData do
  def decode(value, _options) do
    value
  end
end

