# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MultipleFolderEventsResponse do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"data"
  ]

  @type t :: %__MODULE__{
    :"data" => [OpenXchangeClient.Model.MultipleEventData.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MultipleFolderEventsResponse do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"data", :list, OpenXchangeClient.Model.MultipleEventData, options)
  end
end

