# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.MultifactorFinishRegistrationData do
  @moduledoc """
  The provider specific parameters required to finish a device registration.
  """

  @derive [Poison.Encoder]
  defstruct [
    :secret_code,
    :clientData,
    :registrationData
  ]

  @type t :: %__MODULE__{
          :secret_code => String.t() | nil,
          :clientData => String.t() | nil,
          :registrationData => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.MultifactorFinishRegistrationData do
  def decode(value, _options) do
    value
  end
end
