# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.OAuthAccountInteraction do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :authUrl,
    :type,
    :token,
    :uuid
  ]

  @type t :: %__MODULE__{
          :authUrl => String.t() | nil,
          :type => String.t() | nil,
          :token => String.t() | nil,
          :uuid => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.OAuthAccountInteraction do
  def decode(value, _options) do
    value
  end
end
