# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.OAuthClientData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :name,
    :description,
    :website,
    :icon
  ]

  @type t :: %__MODULE__{
          :id => String.t() | nil,
          :name => String.t() | nil,
          :description => String.t() | nil,
          :website => String.t() | nil,
          :icon => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.OAuthClientData do
  def decode(value, _options) do
    value
  end
end
