# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.OAuthServiceMetaData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"id",
    :"displayName",
    :"availableScopes"
  ]

  @type t :: %__MODULE__{
    :"id" => String.t | nil,
    :"displayName" => String.t | nil,
    :"availableScopes" => [String.t] | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.OAuthServiceMetaData do
  def decode(value, _options) do
    value
  end
end

