# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.PasswordChangeBody do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"old_password",
    :"new_password"
  ]

  @type t :: %__MODULE__{
    :"old_password" => String.t | nil,
    :"new_password" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.PasswordChangeBody do
  def decode(value, _options) do
    value
  end
end

