# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.Resource do
  @moduledoc """
  In case the parameter 'extendedEntities' is set to 'true' and the entity is a resource then this field contains the data of this resource. 
  """

  @derive [Poison.Encoder]
  defstruct [
    :id,
    :display_name,
    :name,
    :mailaddress,
    :availability,
    :description,
    :last_modified,
    :last_modified_utc
  ]

  @type t :: %__MODULE__{
          :id => integer() | nil,
          :display_name => String.t() | nil,
          :name => String.t() | nil,
          :mailaddress => String.t() | nil,
          :availability => boolean() | nil,
          :description => String.t() | nil,
          :last_modified => String.t() | nil,
          :last_modified_utc => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.Resource do
  def decode(value, _options) do
    value
  end
end
