# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ResolveShareReferenceElement do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"reference"
  ]

  @type t :: %__MODULE__{
    :"reference" => String.t
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ResolveShareReferenceElement do
  def decode(value, _options) do
    value
  end
end

