# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.SharedAttachments do
  @moduledoc """
  The shared attachments object
  """

  @derive [Poison.Encoder]
  defstruct [
    :language,
    :enabled,
    :autodelete,
    :expiryDate,
    :password
  ]

  @type t :: %__MODULE__{
          :language => String.t() | nil,
          :enabled => boolean() | nil,
          :autodelete => boolean() | nil,
          :expiryDate => integer() | nil,
          :password => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.SharedAttachments do
  def decode(value, _options) do
    value
  end
end
