# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ShareTargetData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"module",
    :"folder",
    :"item"
  ]

  @type t :: %__MODULE__{
    :"module" => String.t | nil,
    :"folder" => String.t | nil,
    :"item" => String.t | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ShareTargetData do
  def decode(value, _options) do
    value
  end
end

