# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.ShareLinkData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"url",
    :"entity",
    :"is_new",
    :"expiry_date",
    :"password",
    :"includeSubfolders",
    :"meta"
  ]

  @type t :: %__MODULE__{
    :"url" => String.t | nil,
    :"entity" => integer() | nil,
    :"is_new" => boolean() | nil,
    :"expiry_date" => integer() | nil,
    :"password" => String.t | nil,
    :"includeSubfolders" => boolean() | nil,
    :"meta" => map() | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.ShareLinkData do
  def decode(value, _options) do
    value
  end
end

