# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.TaskData do
  @moduledoc """
  
  """

  @derive [Poison.Encoder]
  defstruct [
    :"status",
    :"percent_completed",
    :"actual_costs",
    :"actual_duration",
    :"after_complete",
    :"billing_information",
    :"target_costs",
    :"target_duration",
    :"priority",
    :"currency",
    :"trip_meter",
    :"companies",
    :"date_completed",
    :"start_time",
    :"end_time",
    :"title",
    :"start_date",
    :"end_date",
    :"note",
    :"alarm",
    :"recurrence_type",
    :"days",
    :"day_in_month",
    :"month",
    :"interval",
    :"until",
    :"notification",
    :"participants",
    :"users",
    :"occurrences",
    :"uid",
    :"organizer",
    :"sequence",
    :"confirmations",
    :"organizerId",
    :"principal",
    :"principalId",
    :"full_time",
    :"id",
    :"created_by",
    :"modified_by",
    :"creation_date",
    :"last_modified",
    :"folder_id",
    :"categories",
    :"private_flag",
    :"color_label",
    :"number_of_attachments",
    :"lastModifiedOfNewestAttachmentUTC"
  ]

  @type t :: %__MODULE__{
    :"status" => integer() | nil,
    :"percent_completed" => integer() | nil,
    :"actual_costs" => float() | nil,
    :"actual_duration" => String.t | nil,
    :"after_complete" => integer() | nil,
    :"billing_information" => String.t | nil,
    :"target_costs" => float() | nil,
    :"target_duration" => String.t | nil,
    :"priority" => integer() | nil,
    :"currency" => String.t | nil,
    :"trip_meter" => String.t | nil,
    :"companies" => String.t | nil,
    :"date_completed" => integer() | nil,
    :"start_time" => integer() | nil,
    :"end_time" => integer() | nil,
    :"title" => String.t | nil,
    :"start_date" => integer() | nil,
    :"end_date" => integer() | nil,
    :"note" => String.t | nil,
    :"alarm" => integer() | nil,
    :"recurrence_type" => integer() | nil,
    :"days" => integer() | nil,
    :"day_in_month" => integer() | nil,
    :"month" => integer() | nil,
    :"interval" => integer() | nil,
    :"until" => integer() | nil,
    :"notification" => boolean() | nil,
    :"participants" => [OpenXchangeClient.Model.TaskParticipant.t] | nil,
    :"users" => [OpenXchangeClient.Model.TaskUser.t] | nil,
    :"occurrences" => integer() | nil,
    :"uid" => String.t | nil,
    :"organizer" => String.t | nil,
    :"sequence" => integer() | nil,
    :"confirmations" => [OpenXchangeClient.Model.TaskConfirmation.t] | nil,
    :"organizerId" => integer() | nil,
    :"principal" => String.t | nil,
    :"principalId" => integer() | nil,
    :"full_time" => boolean() | nil,
    :"id" => String.t | nil,
    :"created_by" => String.t | nil,
    :"modified_by" => String.t | nil,
    :"creation_date" => integer() | nil,
    :"last_modified" => integer() | nil,
    :"folder_id" => String.t | nil,
    :"categories" => String.t | nil,
    :"private_flag" => boolean() | nil,
    :"color_label" => integer() | nil,
    :"number_of_attachments" => integer() | nil,
    :"lastModifiedOfNewestAttachmentUTC" => integer() | nil
  }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.TaskData do
  import OpenXchangeClient.Deserializer
  def decode(value, options) do
    value
    |> deserialize(:"participants", :list, OpenXchangeClient.Model.TaskParticipant, options)
    |> deserialize(:"users", :list, OpenXchangeClient.Model.TaskUser, options)
    |> deserialize(:"confirmations", :list, OpenXchangeClient.Model.TaskConfirmation, options)
  end
end

