# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.TokensData do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :session,
    :user,
    :user_id,
    :context_id,
    :locale
  ]

  @type t :: %__MODULE__{
          :session => String.t() | nil,
          :user => String.t() | nil,
          :user_id => integer() | nil,
          :context_id => integer() | nil,
          :locale => String.t() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.TokensData do
  def decode(value, _options) do
    value
  end
end
