# NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
# https://openapi-generator.tech
# Do not edit the class manually.

defmodule OpenXchangeClient.Model.UserSearchBody do
  @moduledoc """

  """

  @derive [Poison.Encoder]
  defstruct [
    :pattern,
    :startletter,
    :last_name,
    :first_name,
    :display_name,
    :orSearch,
    :emailAutoComplete
  ]

  @type t :: %__MODULE__{
          :pattern => String.t() | nil,
          :startletter => boolean() | nil,
          :last_name => String.t() | nil,
          :first_name => String.t() | nil,
          :display_name => String.t() | nil,
          :orSearch => boolean() | nil,
          :emailAutoComplete => boolean() | nil
        }
end

defimpl Poison.Decoder, for: OpenXchangeClient.Model.UserSearchBody do
  def decode(value, _options) do
    value
  end
end
